### ISSUE TITLE
PEPPOL gives nothing...

### ISSUE THREAD

**Issue by QAnders** [TimLuq/schematron-runner#4]
Not sure if this project is alive or not but firstly, thanks for some important pointers I learned from in the code! :)

I need to run a `.sch` to validate PEPPOL messages. The SCH can be found here: https://github.com/OpenPEPPOL/peppol-bis-invoice-3/blob/master/rules/sch/PEPPOL-EN16931-UBL.sch

Seems the SCH is not loaded properly though:

```
// parseSchematron()
{
  functions: Map {},
  namespaceMap: Map {},
  patternRuleMap: Map {},
  ruleMap: Map {}
}

// validate()
{ errors: [], ignored: [], passed: [], warnings: [] }
```

Is there some specific limitations to the package?

**Comment by TimLuq** [comment]
Unfortunately all major XML dependencies only support XPath 1.0. The PEPPOL schematron definitions are using some 2.0 features and maybe even one or two 3.0 features.

I have something in the works for handling this using WASM. But it is far from ready. I recommend using Java libraries to validate any sufficiently complex XML structure as things currently stand.

**Comment by QAnders** [comment]
Hej Tim! Checking back on this... any though on getting it going?

I've built a "work-around" using `xslt3` and `saxon-js` but I have had some performance issues with it so started looking if someone had built something the past few years but it seems a not very well traveled path... :)
